redis :
  host : 172.22.181.74
  password : seatelRedis

rabbitmq :
  addresses : 172.22.181.74:5672
  password : Rabbitmq123

database :
  lemon :
    url : jdbc:mysql://localhost:6446/lemon?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username : lemon
    password : lemon@123
  primary :
    url : jdbc:mysql://localhost:6446/seatelpay_pwm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username : pwm
    password : pwm

eureka :
  zone : http://172.22.181.72:9002/eureka/,http://172.22.181.73:9002/eureka/

pwm :
  recharge :
    #营业厅充值签名KEY值
    HALLKEY : PWM123456789002
    #营业厅ftp服务器配置
    hall-sftp:
       ip: 192.168.3.38
       port: 22
       name: payment
       password: Hisunpay2017
       connectTimeout: 120000
  sftp :
    ip : 172.22.181.80
    port : 9898
    name : seatel
    password : seatel
    connectTimeout : 120000
  chk :
    remotePath : /pwm/
    localPath : /data/pwm/data/chk/
    hallLocalPath: /data/pwm/data/hall/
    #营业厅指定对账文件目录地址
    hallRemotePath: /data/pwm/data/hall/