redis :
  host : 10.9.10.120
  password : redis@123

rabbitmq :
  addresses : 10.9.10.130:5672
  password : Rabbitmq123

#Multiple dataSources
dataSource :
  lemon :
      type : com.alibaba.druid.pool.DruidDataSource
      driverClassName : com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://10.9.10.120:3306/lemon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username : lemon
      password : lemon@123
      initialSize : 5
      minIdle : 5
      maxActive : 20
      # 配置获取连接等待超时的时间
      maxWait : 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis : 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis : 300000
      validationQuery : SELECT 1
      testWhileIdle : true
      testOnBorrow : false
      testOnReturn : false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements : true
      maxPoolPreparedStatementPerConnectionSize : 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters : stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat : true
  primary :
      type : com.alibaba.druid.pool.DruidDataSource
      driverClassName : com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://10.9.10.120:3306/xxpay_pwm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username : pwm
      password : pwm
      initialSize : 5
      minIdle : 5
      maxActive : 20
      # 配置获取连接等待超时的时间
      maxWait : 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis : 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis : 300000
      validationQuery : SELECT 1
      testWhileIdle : true
      testOnBorrow : false
      testOnReturn : false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements : true
      maxPoolPreparedStatementPerConnectionSize : 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters : stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat : true


eureka :
  zone : http://10.9.10.130:9002/eureka/
  instance:
   # ip-address: 219.135.153.39
   preferIpAddress : true
lemon:
  batch:
    enabled : true
