spring :
  profiles :
    active : dev
  #数据源
  datasource :
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/seatelpay?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username : seatelpay
    password : seatelpay
    druid :
      initialSize : 5
      minIdle : 5
      maxActive : 20
      # 配置获取连接等待超时的时间
      maxWait : 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
      timeBetweenEvictionRunsMillis : 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒 
      minEvictableIdleTimeMillis : 300000
      validationQuery : SELECT 1
      testWhileIdle : true
      testOnBorrow : false
      testOnReturn : false
      # 打开PSCache，并且指定每个连接上PSCache的大小 
      poolPreparedStatements : true
      maxPoolPreparedStatementPerConnectionSize : 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
      filters : stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat : true
      monitor :
        loginUsername : druid
        loginPassword : druid123
  redis :
    database : 0
    host : 120.76.22.56
    port : 6379
    password : Hisunpay2017
    pool : 
      #连接池最大连接数（使用负值表示没有限制）
      max-active : 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait : 10000
      # 连接池中的最大空闲连接
      max-idle : 8
      # 连接池中的最小空闲连接
      min-idle : 1
    #连接超时时间（毫秒）
    timeout : 10000
    #默认缓存过期时间(秒)
    default-expiration : 600
  http :
    encoding :
      force : true
      charset : UTF-8
      enabled : true
  mvc :
    throw-exception-if-no-handler-found : true
  resources :
    #是否开启默认的资源处理，默认为true, 为false swagger不可用
    add-mappings : true
  messages :
    basename : i18n/messages
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1,单位 s
    cache-seconds : 10
    encoding : UTF-8
  thymeleaf :
    cache : false
  jackson :
    serialization : 
      write_dates_as_timestamps : false
    
logging :
  config : classpath:config/logback-spring.xml
  level :
    root : DEBUG
    
lemon :
  idgen :
    #每次从reids申请Id的数量
    delta : 500
    #在redis里Id key 的前缀，prefix+"."+ applicationName,申请ID key作为hash key.
    prefix : IDGEN
    #ID sequence 最大值，默认值无穷大，配置方式是在max-value 下配置key 及长度 
    max-value :
      #msgId key
      MSGID.DM3 : 999
      USER_ID : 999999  
    #通用的ID sequence 长度
    common-id-sequence-len : 10
    autogen :
      DOPackage : com.hisun.lemon.*.entity
    #msgId sequence 长度
    msg-id-sequence-len : 3
  locale :
    default : zh_cn
    
mybatis: 
 # mapperLocations: classpath:mapper/*.xml
 # typeAliasesPackage : 对应我们的实体类所在的包
 # config : mybatis-config.xml
 # typeHandlersPackage 扫描typeHandlers的包
  
swagger :
  show : true
  swaggerDescription : "请使用swagger做好api文档"
  swaggerServiceUrl : "github 目录"

feign :
  httpclient :
    enabled : true
    #max connection for http client
    maxTotal : 30
    #max per route connection for http client
    defaultMaxPerRoute : 5
    #Returns the duration of time which this connection can be safely kept idle
    alive : 60000
    #idle timeout for connection /ms
    idleTimeoutMillis : 30000
    #clear expire and idle timeout http connections schedule rate
    clearConnectionsRate : 30000
  
#测试参数  
parameters :
  env : default
