spring :
  redis :
    database : 0
    host : ${redis.host:192.168.3.39}
    port : 6379
    password : ${redis.password:Hisunpay2017}
    pool :
      #连接池最大连接数（使用负值表示没有限制）
      max-active : 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait : 10000
      # 连接池中的最大空闲连接
      max-idle : 8
      # 连接池中的最小空闲连接
      min-idle : 1
    #连接超时时间（毫秒）
    timeout : 10000
  #see rabbitProperties
  rabbitmq :
    addresses : ${rabbitmq.addresses:192.168.3.38:5672}
    virtualHost : /lemon
    username : rabbitmq
    password : ${rabbitmq.password:Rabbitmq123}
    requestedHeartbeat : 10
    publisherConfirms : true
    publisherReturns : true
    connectionTimeout : 10000
    cache:
      channel :
        size : 5
    listener :
      concurrency : 1
      maxConcurrency : 5
      idleEventInterval : 60000
      prefetch : 10
      transactionSize : 10
  cloud :
    stream :
      defaultBinder : rabbit
      bindings :
        input :
          destination : ${spring.application.name}
          group : ${spring.application.name}
          consumer :
            enabled : true
            concurrency : 1
            maxConcurrency : 5
            maxAttempts : 1
            durableSubscription : true
            prefetch : 10
            txSize : 10
          producer :
            deliveryMode : PERSISTENT
        #channel
        output :
          enable : true
          #binder topic
          destination : ${spring.application.name}
          producer :
            deliveryMode : PERSISTENT
        output3 :
          enable : true
          destination : TFM
          producer :
            deliveryMode : PERSISTENT
        output6 :
          enable : true
          destination : BIL
          producer :
            deliveryMode : PERSISTENT


lemon :
  #Multiple dataSources
  dataSources :
    primary :
      type : com.alibaba.druid.pool.DruidDataSource
      driverClassName : oracle.jdbc.driver.OracleDriver
      url : jdbc:oracle:thin:@10.9.10.120:1521/orcl
      username : 'c##xxpay_pwm'
      password : pwm
    lemon :
      type : com.alibaba.druid.pool.DruidDataSource
      driverClassName : oracle.jdbc.driver.OracleDriver
      url : jdbc:oracle:thin:@10.9.10.120:1521/orcl
      username : 'c##xxpay_lemon'
      password : lemon
  #dynamic datasource
  dynamicDataSource :
    enabled : true
    defaultDataSource : primary
  idgen :
    #每次从reids申请Id的数量
    delta :
      default : 500
      MSGID_ : 1000
      REQUESTID_ : 1000
    #ID sequence 最大值，默认值无穷大，配置方式是在max-value 下配置key 及长度
    max-value :
      #msgId key
      MSGID_ : 999999999
      REQUESTID_ : 999999999
  cache :
    jcache :
      config : classpath:config/ehcache3.xml
      provider : org.ehcache.jsr107.EhcacheCachingProvider
    redis :
      database : 1
      host : ${redis.host:192.168.3.39}
      port : 6379
      password : ${redis.password:Hisunpay2017}
      pool :
        #连接池最大连接数（使用负值表示没有限制）
        max-active : 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait : 10000
        # 连接池中的最大空闲连接
        max-idle : 8
        # 连接池中的最小空闲连接
        min-idle : 1
      #连接超时时间（毫秒）
      timeout : 10000
      #默认缓存过期时间(秒)
      defaultExpiry : 600
  #default locale for application
  locale :
    defaultLocale : zh_cn
    supportLocales : zh_cn,en_us
  #spring scheuling configuration
  schedule :
    threadPool :
      poolSize : 10
      waitForTasksToCompleteOnShutdown : true
      awaitTerminaltionSeconds : 30
  # distributed lock dependence on redisson
  redisson :
    enabled : true
    mode : single
    address : ${redis.host:192.168.3.39}:6379
    password : ${redis.password:Hisunpay2017}
    poolSize : 30
    idleSize : 5
    idleTimeout : 60000
    connectionTimeout : 10000
    timeout : 5000
  pagehelper :
    defaultPageNum : 1
    defaultPageSize : 8
  feign :
    # feign client validation
    validation :
      enabled : true
  sql :
    # print sql set 'DEBUG'
    level : DEBUG
