redis :
  host : 192.168.100.111
  port : 6679
  password : 'Redis#123'

rabbitmq :
  addresses : 192.168.100.111:1567
  password : 'Rabbitmq#123'

lemon :
    #Multiple dataSources
    dataSources :
      primary :
        type : com.alibaba.druid.pool.DruidDataSource
        driverClassName : oracle.jdbc.driver.OracleDriver
        url : jdbc:oracle:thin:@192.168.100.201:1521/orcl
        username : 'c##xxpay_pwm'
        password : pwm
      lemon :
        type : com.alibaba.druid.pool.DruidDataSource
        driverClassName : oracle.jdbc.driver.OracleDriver
        url : jdbc:oracle:thin:@192.168.100.201:1521/orcl
        username : 'c##xxpay_lemon'
        password : lemon
    #dynamic datasource
    dynamicDataSource :
      enabled : true
      defaultDataSource : primary

eureka :
  zone : http://192.168.100.111:9002/eureka/


pwm :
  sftp :
    ip : 192.168.100.100
    port : 9898
    name : xxpay
    password : 'Xxpay#123'
    connectTimeout : 2000
  chk :
    remotePath : /home/xxpay/data/pwm/
    localPath : /data/pwm/data/
