redis :
  host : 10.9.10.120
  password : redis@123

rabbitmq :
  addresses : 10.9.10.130:5672
  password : Rabbitmq123

lemon :
  dataSource :
    lemon :
      url : jdbc:oracle:thin:@10.9.10.120:1521/orcl
      username : 'c##lemon'
      password : lemon
    primary :
      url : jdbc:oracle:thin:@10.9.10.120:1521/orcl
      username : 'c##xxpay_pwm'
      password : pwm
  batch :
    enabled : true

eureka :
  zone : http://10.9.10.130:9002/eureka/


pwm :
  sftp :
    ip : 10.9.10.127
    port : 22
    name : oper
    password : h4y]nrTDvq8,XjBG
    connectTimeout : 2000
  chk :
    remotePath : /home/oper/data/pwm/
    localPath : /home/oper/data/localchk/pwm/
  transference :
    path : http://192.168.9.103:8081/xiaoxiangPay-api/nfcRecharge/resultNotice
