redis :
  host : 192.168.3.39
  password : Hisunpay2017

rabbitmq :
  addresses : 192.168.3.38:5672
  password : Rabbitmq123

database :
  lemon :
    url : jdbc:mysql://119.23.126.119:3306/lemon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username : lemon
    password : lemon@123
  primary :
    url : jdbc:mysql://119.23.126.119:3306/seatelpay_pwm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username : pwm
    password : pwm

eureka :
  zone : http://192.168.3.38:9002/eureka/,http://192.168.3.39:9012/eureka/