redis :
  host : 172.22.181.74
  password : seatelRedis

rabbitmq :
  addresses : 172.22.181.74:5672
  password : Rabbitmq123

database :
  lemon :
    url : jdbc:mysql://localhost:6446/lemon?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username : lemon
    password : lemon@123
  primary :
    url : jdbc:mysql://localhost:6446/seatelpay_pwm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username : pwm
    password : pwm

eureka :
  zone : http://172.22.181.72:9002/eureka/,http://172.22.181.73:9002/eureka/