redis :
  host : 10.9.10.120
  port : 6379
  password : redis@123

rabbitmq :
  addresses : 10.9.10.130:5672
  password : Rabbitmq123

lemon :
    #Multiple dataSources
    dataSources :
      primary :
        type : com.alibaba.druid.pool.DruidDataSource
        driverClassName : oracle.jdbc.driver.OracleDriver
        url : jdbc:oracle:thin:@10.9.10.120:1521/orcl
        username : 'c##xxpay_pwm'
        password : pwm
      lemon :
        type : com.alibaba.druid.pool.DruidDataSource
        driverClassName : oracle.jdbc.driver.OracleDriver
        url : jdbc:oracle:thin:@10.9.10.120:1521/orcl
        username : 'c##xxpay_lemon'
        password : lemon
    #dynamic datasource
    dynamicDataSource :
      enabled : true
      defaultDataSource : primary

eureka :
  zone : http://10.9.10.130:9002/eureka/


pwm :
  sftp :
    ip : 10.9.10.127
    port : 22
    name : oper
    password : h4y]nrTDvq8,XjBG
    connectTimeout : 2000
  chk :
    remotePath : /home/oper/data/pwm/
    localPath : /app/data/localchk/pwm/
  transference :
    path : http://192.168.9.104:8081/xiaoxiangPay-api/nfcRecharge/resultNotice
