CREATE TABLE `pwm_wdc_order` (
  `order_no` varchar(20) NOT NULL COMMENT '订单号',
  `order_tm` char(14) NOT NULL COMMENT '订单时间',
  `order_exp_tm` date NOT NULL COMMENT '订单失效时间',
  `acc_tm` date NOT NULL COMMENT '记账时间',
  `order_ccy` char(3) NOT NULL COMMENT '币种',
  `order_succ_tm` date NOT NULL COMMENT '订单成功时间',
  `wc_type` varchar(2) NOT NULL COMMENT '提现类型 11:自主提现 21:自动结算',
  `corp_bus_typ` varchar(2) NOT NULL COMMENT '合作业务类型 02:单笔代扣 04:网银支付 05:积分减扣 06:提现',
  `corp_bus_sub_typ` varchar(4) NOT NULL COMMENT '合作业务子类型 02:单笔代扣 0202:支付 04:网银支付 0402:支付 05:积分减扣 0502:减扣 06:提现 0601:提现',
  `wc_apply_amt` decimal(13,2) NOT NULL COMMENT '申请提现金额',
  `wc_act_amt` decimal(13,2) NOT NULL COMMENT '实际提现金额',
  `fee_amt` decimal(9,2) NOT NULL COMMENT '手续费金额',
  `pay_urge_flg` varchar(1) NOT NULL COMMENT '付款加急标识',
  `user_id` varchar(20) NOT NULL COMMENT '内部用户编号',
  `user_nm` varchar(60) NOT NULL COMMENT '用户/商户名称',
  `agr_no` varchar(20) NOT NULL COMMENT '签约协议号',
  `cap_corg_no` varchar(16) NOT NULL COMMENT '资金合作机构号',
  `cap_crd_no` varchar(30) NOT NULL COMMENT '资金卡号',
  `cap_crd_typ` varchar(1) NOT NULL COMMENT '资金卡账户类型 0:借记卡 1:信用卡 2:准贷记卡 3:储蓄账户',
  `cap_crd_nm` varchar(60) NOT NULL COMMENT '资金卡账户姓名',
  `wc_remark` varchar(100) DEFAULT NULL COMMENT '提现备注',
  `ntf_mbl` varchar(20) NOT NULL COMMENT '通知的手机号',
  `order_sts` varchar(2) NOT NULL COMMENT '订单状态 W1:系统受理中 W2:资金流出已受理 S1:付款成功 F1:付款失败 F2:付款核销 R9:审批拒绝',
  `rsp_order_no` varchar(20) NOT NULL COMMENT '资金流出模块订单号',
  `rsp_succ_tm` date NOT NULL COMMENT '资金流出模块成功时间',
  `bus_cnl` varchar(5) NOT NULL COMMENT '业务受理渠道',
  `user_ip_adr` varchar(15) NOT NULL COMMENT '用户操作IP地址',
  `user_opr_sys` varchar(30) NOT NULL COMMENT '用户操作系统信息',
  `user_brow_info` varchar(30) NOT NULL COMMENT '用户浏览器信息',
  `modify_time` datetime NOT NULL COMMENT '修改时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `tm_smp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  PRIMARY KEY (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1
